name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - cicd
      - cicd-docker-image

jobs:
  build-deploy:
    name: Build and Deploy HRMS application
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Importing MySQL
        env:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_DATABASE: hrms
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root # Default username for mysql is root and default password is also root
        run: |
          sudo /etc/init.d/mysql start
          mysql \
          -h"${DB_HOST}" \
          -P"${DB_PORT}" \
          -u"${DB_USER}" \
          -p"${DB_PASSWORD}" \
          -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hrms-github-actions:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hrms-github-actions:latest
