name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - cicd

jobs:
  build-deploy:
    name: Build and Deploy HRMS application
    runs-on: self-hosted-runner
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
