name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - cicd

jobs:
  build-deploy:
    name: Build and Deploy HRMS application
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Importing MySQL
        env:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_DATABASE: hrms
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
        run: |
          sudo /etc/init.d/mysql start
          mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"

#      - name: Import Database Schema
#        run: |


#      - name: Unit Tests
#        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
